# Roles
roles:
  guest: 'guest'
  member: 'member'
  author: 'author'
  moderator: 'moderator'
  admin: 'admin'

# Roles level
rolesLevel:
  guest: 0
  member: 1
  author: 2
  moderator: 3
  admin: 4
