# Logs level // error / warn / info / verbose / debug / silly
logsLevel:
  console: 'silly'

# Mongoose
mongoose:
  connectionString: 'mongodb://localhost/wikidb'

# Roles
roles:
  guest: 'guest'
  member: 'member'
  author: 'author'
  moderator: 'moderator'
  admin: 'admin'

# Roles level
rolesLevel:
  guest: 0
  member: 1
  author: 2
  moderator: 3
  admin: 4

# Bcrypt salt rounds
saltRounds: 10

# Winston logs level
winston:
  levels:
    error: 0
    warn: 1
    info: 2
    verbose: 3
    debug: 4
    data: 5
    silly: 6
  colors:
    error: 'red'
    warn: 'yellow'
    info: 'green'
    verbose: 'cyan'
    debug: 'blue'
    data: 'magenta'
    silly: 'grey'

